repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=2048]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: go fmt
        language: golang
        types: [go]
        pass_filenames: true
        verbose: true
      - id: lint
        name: lint
        entry: golangci-lint run
        language: golang
        types: [go]
        pass_filenames: true
        verbose: true
      - id: test
        name: test
        entry: go test -coverprofile=coverage.out
        language: golang
        types: [go]
        pass_filenames: false
        verbose: true
      - id: coverage
        name: coverage
        entry: go tool cover -func=coverage.out
        language: golang
        types: [go]
        pass_filenames: false
        verbose: true
